output_path: "/scratch/indikar_root/indikar1/cstansbu/bj_10x_sc/"
inputs: "config/fastq_paths.txt"
ref_path: "/nfs/turbo/umms-indikar/shared/projects/HSC/data/RefGenome/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz" 
transcript_path: "/nfs/turbo/umms-indikar/shared/projects/HSC/data/RefGenome/Homo_sapiens.GRCh38.cdna.all.fa.gz" 
gtf_path: "/nfs/turbo/umms-indikar/shared/projects/HSC/data/RefGenome/Homo_sapiens.GRCh38.107.gtf"
expected_cells: 10000
barcode_whitelist: "/nfs/turbo/umms-indikar/shared/projects/HSC/data/10xBarcoded_SingleCell/3M-february-2018.txt"
minimap2_args: "-ax splice -uf --secondary=no --MD" 
umi_distance: 1
threads: 36
scanpy_params:
    target_sum: 1000000
    min_genes: 500
    min_cells: 10
